spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parking
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


